# Generated by Django 4.2.29 on 2026-05-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='material_type',
            field=models.CharField(choices=[('recycled_polyester', 'Recycled Polyester'), ('virgin_polyester', 'Virgin Polyester'), ('cotton', 'Cotton'), ('organic_cotton', 'Organic Cotton'), ('conventional_cotton', 'Conventional Cotton'), ('linen', 'Linen'), ('hemp', 'Hemp'), ('wool', 'Wool'), ('nylon', 'Nylon'), ('silk', 'Silk'), ('recycled_cardboard', 'Recycled Cardboard'), ('virgin_paper', 'Virgin Paper'), ('recycled_plastic_pet', 'Recycled Plastic PET'), ('virgin_plastic_pet', 'Virgin Plastic PET'), ('bioplastic_pla', 'Bioplastic PLA'), ('glass', 'Glass'), ('aluminum_recycled', 'Recycled Aluminum'), ('aluminum_virgin', 'Virgin Aluminum'), ('steel', 'Steel'), ('copper', 'Copper'), ('lithium_ion_battery', 'Lithium-ion Battery'), ('bamboo', 'Bamboo'), ('cork', 'Cork'), ('hardwood_timber', 'Hardwood Timber'), ('concrete', 'Concrete')], default='cotton', max_length=50),
        ),
    ]
