# Generated by Django 4.2.29 on 2026-05-19 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoShop', '0004_alter_review_options_alter_review_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
